version: '3'

services:
  jekyll:
    image: jekyll/jekyll
    container_name: debian-brasil
    environment:
        - JEKYLL_ENV=docker
    command: jekyll serve --watch --incremental
    ports:
        - 4000:4000
    volumes:
        - ./:/srv/jekyll
